### ISSUE TITLE
Registration reduces privacy exposure

### ISSUE THREAD

**Issue by mcr** [pthubert/non-broadcast-access-architecture#1]
Bob says:

Bob Hinden <bob.hinden@gmail.com> wrote:
    > Excuse the top post.  As long as a node can listen to all traffic
    > (e.g., promiscuous mode and/or receive radio signals) that is
    > unencrypted there is a privacy problem.  Seems to me like registration
    > reduces the exposure a bit (requires more work), but doesn’t make it go
    > away.  I suspect the draft needs to discuss the traceoffs here.

**Comment by pthubert** [comment]
Added security and privacy sections
